### ISSUE TITLE
Python 3.7.10 AttributeError

### ISSUE THREAD

**Issue by cell2749** [RalphMao/PyTimer#1]
https://github.com/RalphMao/PyTimer/blob/33ff33eaae10a94e437dacbeaa96207fc12e88c9/pytimer/timer.py#L47
AttributeError: 'function' object has no attribute 'func_name'

Changed to ```__name__``` on my local machine and it works. As per suggestion: https://stackoverflow.com/a/60108055/7231063

**Comment by RalphMao** [comment]
Thank you for pointing that out - just fixed this problem
